✨ Create a pre-commit hook that calls apply config

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,26 +1,15 @@
 #!/bin/bash
 
-# To apply the changes run
-# $ apply-hooks ~/bin
+# Activate specific venv and run your script
+/Users/lnola/.python/venv/bin/python ~/bin/scripts/apply-config/apply_config.py
 
-$HOME/bin/scripts/apply-config.sh
+# Capture the exit code of the Python script
+status=$?
 
-# TODO: Turn on when apply-config.sh is ready
-# # Collect the staged files
-# STAGED_FILES=$(git diff --cached --name-only --diff-filter=d)
+if [ $status -ne 0 ]; then
+  echo "Pre-commit check failed"
+  exit $status
+fi
 
-# # Check if there are staged files
-# if [ -z "$STAGED_FILES" ]; then
-#     echo "No files are staged for commit"
-# else
-#     # Call the external script with the staged files as arguments
-#     $HOME/bin/scripts/apply-config.sh $HOME/bin/scripts/.config.json $STAGED_FILES
-#     if [ $? -ne 0 ]; then
-#         echo "Failed to apply the configuration to the staged files"
-#         exit 1
-#     fi
-# fi
-
-# # Exit successfully so the commit can proceed
-# exit 0
+exit 0
 
